import '../styles/globals.scss';
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className="flex justify-center bg-white text-black">
      <div className="w-full max-w-[1920px]">{children}</div>
    </body>
  </html>
  );
}
